apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-client
  template:
    metadata:
      labels:
        app: go-client
    spec:
      containers:
        - name: go-client
          image: xuetaoli/go-client:latest
          env:
            - name: SERVER_ADDRESS
              value: "go-server-service:8080"  # 通过 Kubernetes Service 名称访问服务端
